
<?php
$array = array(
            array(
                "id"=>"37",
                "ptoken"=>"xMs5DOTdGY66",
                "quantity"=>"7",
                "default_size_adon_id"=>"126",
                "default_size_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"126",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Size",
                        "adon_value"=>"XXL",
                        "adon_price"=>"500",
                        "timestamp"=>"1661851408"
                    ),
                 ),
                "default_size_adon_price"=>500,
                "default_size_adon_value"=>"XXL",
                "default_color_adon_id"=>"122",
                "default_color_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"122",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Color",
                        "adon_value"=>"#ffff00",
                        "adon_price"=>"200",
                        "timestamp"=>"1661851338"
                    ),
                ),
                "default_color_adon_price"=>200,
                "default_color_adon_value"=>"#ffff00",
                "default_delivery_adon_id"=>"128",
                "default_delivery_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"128",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Delivery",
                        "adon_value"=>"Lagos",
                        "adon_price"=>"2000",
                        "timestamp"=>"1661851459"
                    ),
                ),
                "default_delivery_adon_price"=>2000,
                "default_delivery_adon_value"=>"Lagos",
                "amount"=>"0",
                "timestamp"=>"1662477283",
                "created"=>"Tue 06 Sep, 2022 15",
                "product_data"=>array(
                "id"=>"110",
                "token"=>"xMs5DOTdGY66",
                "usertoken"=>"D3188JDMXB",
                "productname"=>"Cart",
                "price"=>"2550",
                "price_th"=>"2,550",
                "time"=>"7 day(s)",
                "storename"=>"sdf",
                "expected_delivery_days"=>"0",
                "description"=>"Adding to the cart is all that is here",
                "success"=>true,
                "quantity"=>"17",
                "escrow"=>"1",
                "ip"=>"66.29.137.10",
                "nickname"=>"sdf",
                "store_social_twitter"=>"0",
                "store_social_facebook"=>"0",
                "store_social_instagram"=>"0",
                "totalRating"=>0,
                "img"=>"https://renicloud.infura-ipfs.io/ipfs/Qme4caDtXne2Khm6gau8LoNDTbTDNCerRAjrfzWQ5M7F89"
                ),
                "colorAdons"=> array(
                    array(
                        array(
                            "id"=>"121",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Color",
                            "adon_value"=>"#00ff40",
                            "adon_price"=>"300",
                            "adon_price_th"=>"300",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"122",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Color",
                            "adon_value"=>"#ffff00",
                            "adon_price"=>"200",
                            "adon_price_th"=>"200",
                            "selected"=>1
                        ),
                    ),
                ),
                "deliveryAdons"=>array(
                    array(
                        array(
                            "id"=>"127",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Delivery",
                            "adon_value"=>"Ibadan",
                            "adon_price"=>"500",
                            "adon_price_th"=>"500",
                            "selected"=>0,
                            "id2"=>"128"
                        ),
                        array(
                            "id"=>"128",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Delivery",
                            "adon_value"=>"Lagos",
                            "adon_price"=>"2000",
                            "adon_price_th"=>"2,000",
                                "selected"=>1,
                            "id2"=>"128"
                        ),
                    ),
                ),

                "sizeAdons"=>array(
                    array(
                        array(
                            "id"=>"123",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"XL",
                            "adon_price"=>"300",
                            "adon_price_th"=>"300",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"124",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"Medium",
                            "adon_price"=>"200",
                            "adon_price_th"=>"200",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"125",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"Small",
                            "adon_price"=>"0",
                            "adon_price_th"=>"0",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"126",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"XXL",
                            "adon_price"=>"500",
                            "adon_price_th"=>"500",
                            "selected"=>1
                        ),
                    ),
                ),
                "escrowCharges"=>200,
                "totalAmount"=>2900,
                "totalAmount_th"=>"2,900"
            ),
            array(
                "id"=>"36",
                "ptoken"=>"xMs5DOTdGY66",
                "quantity"=>"1",
                "default_size_adon_id"=>"125",
                "default_size_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"125",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Size",
                        "adon_value"=>"Small",
                        "adon_price"=>"0",
                        "timestamp"=>"1661851391"
                    ),
                ),
                "default_size_adon_price"=>0,
                "default_size_adon_value"=>"Small",
                "default_color_adon_id"=>"122",
                "default_color_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"122",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Color",
                        "adon_value"=>"#ffff00",
                        "adon_price"=>"200",
                        "timestamp"=>"1661851338"
                    ),
                ),
                "default_color_adon_price"=>200,
                "default_color_adon_value"=>"#ffff00",
                "default_delivery_adon_id"=>"127",
                "default_delivery_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"127",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Delivery",
                        "adon_value"=>"Ibadan",
                        "adon_price"=>"500",
                        "timestamp"=>"1661851429"
                    ),
                ),
                "default_delivery_adon_price"=>500,
                "default_delivery_adon_value"=>"Ibadan",
                "amount"=>"0",
                "timestamp"=>"1662477244",
                "created"=>"Tue 06 Sep, 2022 15",
                "product_data"=>array(
                "id"=>"110",
                "token"=>"xMs5DOTdGY66",
                "usertoken"=>"D3188JDMXB",
                "productname"=>"Cart",
                "price"=>"2550",
                "price_th"=>"2,550",
                "time"=>"7 day(s)",
                "storename"=>"sdf",
                "expected_delivery_days"=>"0",
                "description"=>"Adding to the cart is all that is here",
                "success"=>true,
                "quantity"=>"17",
                "escrow"=>"1",
                "ip"=>"66.29.137.10",
                "nickname"=>"sdf",
                "store_social_twitter"=>"0",
                "store_social_facebook"=>"0",
                "store_social_instagram"=>"0",
                "totalRating"=>0,
                "img"=>"https://renicloud.infura-ipfs.io/ipfs/Qme4caDtXne2Khm6gau8LoNDTbTDNCerRAjrfzWQ5M7F89"
                ),
                "colorAdons"=>array(
                    array(
                        array(
                            "id"=>"121",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Color",
                            "adon_value"=>"#00ff40",
                            "adon_price"=>"300",
                            "adon_price_th"=>"300",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"122",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Color",
                            "adon_value"=>"#ffff00",
                            "adon_price"=>"200",
                            "adon_price_th"=>"200",
                            "selected"=>1
                        ),
                    ),
                ),
                "deliveryAdons"=>array(
                    array(
                        array(
                            "id"=>"127",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Delivery",
                            "adon_value"=>"Ibadan",
                            "adon_price"=>"500",
                            "adon_price_th"=>"500",
                            "selected"=>1,
                            "id2"=>"127"
                        ),
                        array(
                            "id"=>"128",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Delivery",
                            "adon_value"=>"Lagos",
                            "adon_price"=>"2000",
                            "adon_price_th"=>"2,000",
                            "selected"=>0,
                            "id2"=>"127"
                        ),
                    ),
                ),
                "sizeAdons"=>array(
                    array(
                        array(
                            "id"=>"123",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"XL",
                            "adon_price"=>"300",
                            "adon_price_th"=>"300",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"124",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"Medium",
                            "adon_price"=>"200",
                            "adon_price_th"=>"200",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"125",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"Small",
                            "adon_price"=>"0",
                            "adon_price_th"=>"0",
                            "selected"=>1
                        ),
                        array(
                            "id"=>"126",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"XXL",
                            "adon_price"=>"500",
                            "adon_price_th"=>"500",
                            "selected"=>0
                        ),
                    ),
                ),
                "escrowCharges"=>200,
                "totalAmount"=>1000,
                "totalAmount_th"=>"900"
            ),
            array(
                "id"=>"36",
                "ptoken"=>"xMs5DOTdGY66",
                "quantity"=>"1",
                "default_size_adon_id"=>"125",
                "default_size_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"125",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Size",
                        "adon_value"=>"Small",
                        "adon_price"=>"0",
                        "timestamp"=>"1661851391"
                    ),
                ),
                "default_size_adon_price"=>0,
                "default_size_adon_value"=>"Small",
                "default_color_adon_id"=>"122",
                "default_color_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"122",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Color",
                        "adon_value"=>"#ffff00",
                        "adon_price"=>"200",
                        "timestamp"=>"1661851338"
                    ),
                ),
                "default_color_adon_price"=>200,
                "default_color_adon_value"=>"#ffff00",
                "default_delivery_adon_id"=>"127",
                "default_delivery_adon_data"=>array(
                    "success"=>true,
                    "data"=>array(
                        "id"=>"127",
                        "producttoken"=>"xMs5DOTdGY66",
                        "adon_type"=>"Delivery",
                        "adon_value"=>"Ibadan",
                        "adon_price"=>"500",
                        "timestamp"=>"1661851429"
                    ),
                ),
                "default_delivery_adon_price"=>500,
                "default_delivery_adon_value"=>"Ibadan",
                "amount"=>"0",
                "timestamp"=>"1662477244",
                "created"=>"Tue 06 Sep, 2022 15",
                "product_data"=>array(
                "id"=>"110",
                "token"=>"xMs5DOTdGY66",
                "usertoken"=>"D3188JDMXB",
                "productname"=>"Cart",
                "price"=>"2550",
                "price_th"=>"2,550",
                "time"=>"7 day(s)",
                "storename"=>"sdf",
                "expected_delivery_days"=>"0",
                "description"=>"Adding to the cart is all that is here",
                "success"=>true,
                "quantity"=>"17",
                "escrow"=>"1",
                "ip"=>"66.29.137.10",
                "nickname"=>"sdf",
                "store_social_twitter"=>"0",
                "store_social_facebook"=>"0",
                "store_social_instagram"=>"0",
                "totalRating"=>0,
                "img"=>"https://renicloud.infura-ipfs.io/ipfs/Qme4caDtXne2Khm6gau8LoNDTbTDNCerRAjrfzWQ5M7F89"
                ),
                "colorAdons"=>array(
                    array(
                        array(
                            "id"=>"121",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Color",
                            "adon_value"=>"#00ff40",
                            "adon_price"=>"300",
                            "adon_price_th"=>"300",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"122",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Color",
                            "adon_value"=>"#ffff00",
                            "adon_price"=>"200",
                            "adon_price_th"=>"200",
                            "selected"=>1
                        ),
                    ),
                ),
                "deliveryAdons"=>array(
                    array(
                        array(
                            "id"=>"127",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Delivery",
                            "adon_value"=>"Ibadan",
                            "adon_price"=>"500",
                            "adon_price_th"=>"500",
                            "selected"=>1,
                            "id2"=>"127"
                        ),
                        array(
                            "id"=>"128",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Delivery",
                            "adon_value"=>"Lagos",
                            "adon_price"=>"2000",
                            "adon_price_th"=>"2,000",
                            "selected"=>0,
                            "id2"=>"127"
                        ),
                    ),
                ),
                "sizeAdons"=>array(
                    array(
                        array(
                            "id"=>"123",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"XL",
                            "adon_price"=>"300",
                            "adon_price_th"=>"300",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"124",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"Medium",
                            "adon_price"=>"200",
                            "adon_price_th"=>"200",
                            "selected"=>0
                        ),
                        array(
                            "id"=>"125",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"Small",
                            "adon_price"=>"0",
                            "adon_price_th"=>"0",
                            "selected"=>1
                        ),
                        array(
                            "id"=>"126",
                            "producttoken"=>"xMs5DOTdGY66",
                            "adon_type"=>"Size",
                            "adon_value"=>"XXL",
                            "adon_price"=>"500",
                            "adon_price_th"=>"500",
                            "selected"=>0
                        ),
                    ),
                ),
                "escrowCharges"=>200,
                "totalAmount"=>100,
                "totalAmount_th"=>"900"
            ),
           
    );
    

    function  sumArray ($array) {
        $total = array();
        foreach ($array as $key => $value){
            array_push($total , $value['totalAmount']);
            $sum = array_sum($total) .'<br>';
        }
        echo $sum;
    }

    sumArray($array);








?>